language: java
jdk:
- openjdk8
before_install:
- "./scripts/preHook.sh"
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- chmod +x gradlew
- "./gradlew setupDecompWorkspace"
deploy:
  provider: releases
  file: build/libs/*-release.jar
  file_glob: true
  skip_cleanup: true
after_success:
- "./scripts/hook.sh"
